const unit = [
    { title: 'Unit' },
    { name: 'unit', symbol: 'unit' },
    { name: 'item', symbol: 'item' },
    { name: 'piece', symbol: 'piece' },
    { name: 'bag', symbol: 'bag' },
    { name: 'cartoon', symbol: 'cartoon' },
    { name: 'pack', symbol: 'pack' },
    { name: 'box', symbol: 'box' },
    { name: 'pallet', symbol: 'pallet' },


    { title: 'Service' },
    { name: 'service', symbol: 'service' },
    { name: 'ticket', symbol: 'ticket' },
    { name: 'room', symbol: 'room' },
    { name: 'seat', symbol: 'seat' },
    { name: 'way', symbol: 'way' },
    { name: 'meal', symbol: 'meal' },


    { title: 'Length' },
    { name: 'millimeter', symbol: 'mm' },
    { name: 'centimeter', symbol: 'cm' },
    { name: 'decimeter', symbol: 'dm' },
    { name: 'meter', symbol: 'm' },
    { name: 'kilometer', symbol: 'km' },
    { name: 'foot', symbol: 'ft' },
    { name: 'inch', symbol: 'in' },
    { name: 'mile', symbol: 'mi' },
    { name: 'yard', symbol: 'yd' },

    { title: 'Volume' },
    { name: 'cubic foot', symbol: 'ft3' },
    { name: 'cubic inch', symbol: 'in3' },
    { name: 'cubic mile', symbol: 'mi3' },
    { name: 'cubic yard', symbol: 'yd3' },
    { name: 'cup', symbol: 'cup' },
    { name: 'Imperial gallon', symbol: 'gal' },
    { name: 'milliliter', symbol: 'mL' },
    { name: 'liter', symbol: 'L' },
    { name: 'Imperial fluid ounce', symbol: 'fl oz' },
    { name: 'Imperial pint', symbol: 'pt' },
    { name: 'Imperial quart', symbol: 'qt' },
    { name: 'tablespoon', symbol: 'tbsp' },
    { name: 'teaspoon', symbol: 'tspn' },

    { title: 'Weight' },
    { name: 'milligram', symbol: 'mg' },
    { name: 'gram', symbol: 'g' },
    { name: 'kilogram', symbol: 'kg' },
    { name: 'carat', symbol: 'CD' },
    { name: 'grain', symbol: 'gr' },
    { name: 'ounce', symbol: 'oz' },
    { name: 'pennyweight', symbol: 'dwt' },
    { name: 'pound', symbol: 'lb' },
    { name: 'stone', symbol: 'st' },
    { name: 'slug', symbol: 'slug' },
    { name: 'metric ton', symbol: 't' },

    { title: 'Area' },
    { name: 'hectare', symbol: 'ha' },
    { name: 'square foot', symbol: 'ft2' },
    { name: 'square meter', symbol: 'm2' },
    { name: 'square kilometer', symbol: 'km2' },
    { name: 'square inch', symbol: 'in2' },
    { name: 'square yard', symbol: 'yd2' },
    { name: 'square mile', symbol: 'mi2' },

    { title: 'Pressure' },
    { name: 'pascal', symbol: 'Pa' },
    { name: 'torr', symbol: 'Torr' },
    { name: 'bar', symbol: 'bar' },
    { name: 'millibar', symbol: 'mb' },
    { name: 'psi', symbol: 'lbf/in2' },

    { title: 'Time' },
    { name: 'day', symbol: 'day' },
    { name: 'hour', symbol: 'hr' },
    { name: 'minute', symbol: 'min' },
    { name: 'year', symbol: 'yr' },

    { title: 'Temperature' },
    { name: 'celsius', symbol: '°C' },
    { name: 'fahrenheit', symbol: '°F' },
    { name: 'kelvin', symbol: 'K' }
]

module.exports = {unit}